### PR TITLE
fix: make LinearRetry behave linearly for all inputs

### LINKED ISSUE #596: LinearRetry is not linear between start and finish
I assume linear retry should go like this:
image

**Case maxTries = 1, what duration should the delay be**
Unsure what the correct behaviour would be (e.g. firstBackOff or maxBackOff or the median between them ?)
Currently it is delay(maxBackOff-firstBackOff)

**Case maxTries = Int.MAX_VALUE**
It should probably the start at firstBackOff and progress linearly towards maxBackOff so that Int.MAX_VALUE increments were done to the delay to get there.
-> currently it starts at 0ms 

You can replicate this behaviour with the following code
```kotlin
    val retrier = LinearRetry(1.seconds,  60.seconds, Int.MAX_VALUE)
    runBlocking {
        while(retrier.hasNext) {
            retrier.retry()
            println(System.currentTimeMillis())
        }
    }
```

### PR DESCRIPTION
**Pull request by ToxicMushroom**
fixes #596

### CODE REVIEW

File: gateway/src/test/kotlin/helper/LinearRetryTest.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+import dev.kord.gateway.retry.LinearRetry
+import kotlinx.coroutines.runBlocking
+import kotlin.test.Test
+import kotlin.time.Duration.Companion.milliseconds
+
+class LinearRetryTest {
+
+    @Test
+    fun testLinearity() {
```
Comment (Lukellmann) [inline gateway/src/test/kotlin/helper/LinearRetryTest.kt:11]: Could you maybe also add tests for extreme cases you described in the issue? (like `1`, `Int.MAX_VALUE`, ...).
Also to make these test independent of real time, the delay-skipping `runTest {}` can be used with `currentTime` for getting the current virtual time.

**Review by Lukellmann — CHANGES_REQUESTED** [review]

File: gateway/src/test/kotlin/helper/LinearRetryTest.kt (hunk 1 above)
Comment (ToxicMushroom) [reply gateway/src/test/kotlin/helper/LinearRetryTest.kt:11]: oh thanks for the tip I didn't know that existed

File: gateway/src/main/kotlin/retry/LinearRetry.kt [hunk 2]
```diff
@@ -42,10 +43,13 @@ public class LinearRetry(
...
         if (!hasNext) error("max retries exceeded")
 
-        tries.incrementAndGet()
-        var diff = (maxBackoff - firstBackoff).inWholeMilliseconds / maxTries
-        diff *= tries.value
-        linearRetryLogger.trace { "retry attempt ${tries.value}, delaying for $diff ms" }
+        // tries/maxTries ratio * (backOffDiff) = retryProgress
+        val ratio = tries.getAndIncrement() / (maxTries - 1).toDouble()
+        val retryProgress =
+            (ratio * (maxBackoff - firstBackoff).inWholeMilliseconds).toLong().milliseconds
```
Comment (Lukellmann) [inline gateway/src/main/kotlin/retry/LinearRetry.kt:49]: If you import [`kotlin.time.times`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/times.html), you can also avoid the conversion here.

File: gateway/src/test/kotlin/helper/LinearRetryTest.kt [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+import kotlin.time.TimeSource
+import kotlin.time.measureTime
+
+class LinearRetryTest {
+
+    @Test
+    fun testLinearity() = runTest {
+        val linearRetry = LinearRetry(1.seconds, 10.seconds, 10)
+        var i = 0
+        val elapsed = TimeSource.Monotonic.measureTime {
```
Comment (Lukellmann) [inline gateway/src/test/kotlin/helper/LinearRetryTest.kt:18]: Using `TimeSource.measureTime` won't work, it doesn't use the virtual [`currentTime`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/current-time.html).

File: gateway/src/main/kotlin/retry/LinearRetry.kt (hunk 2 above)
Comment (ToxicMushroom) [reply gateway/src/main/kotlin/retry/LinearRetry.kt:49]: oh cool, intellij didn't show that so I assumed it didn't exist

File: gateway/src/main/kotlin/retry/LinearRetry.kt [hunk 4]
```diff
@@ -27,7 +28,7 @@ public class LinearRetry(
         require(
             maxBackoff.minus(firstBackoff).isPositive()
         ) { "maxBackoff ${maxBackoff.inWholeMilliseconds} ms needs to be bigger than firstBackoff ${firstBackoff.inWholeMilliseconds} ms" }
-        require(maxTries > 0) { "maxTries needs to be positive but was $maxTries" }
+        require(maxTries > 1) { "maxTries needs to be positive but was $maxTries" }
```
Comment (Lukellmann) [inline gateway/src/main/kotlin/retry/LinearRetry.kt:31]: Just realized that the message should also be updated (`1` is also positive).

File: gateway/src/test/kotlin/helper/LinearRetryTest.kt [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+        val start = currentTime
+
+        while (linearRetry.hasNext) {
+            linearRetry.retry()
+            i++
+        }
+
+        val end = currentTime
+        val elapsed = (end-start).milliseconds
+        assert(elapsed >= 55.seconds)
```
Comment (Lukellmann) [inline gateway/src/test/kotlin/helper/LinearRetryTest.kt:25]: These assertions should use `==` instead of `>=` or `<=` - virtual time is always exact and predictable.

**Review by Lukellmann — COMMENTED** [review]
Just two last things - then we should be good to go.

**Review by Lukellmann — APPROVED** [review]
Thanks for your efforts!
