### PR TITLE
Fix everyone mention

### LINKED ISSUE #94: Trying to mention the everyone role results in a malformed @@everyone mention in the client
```kotlin
channel.createMessage(guild.everyoneRole.mention)
```

results in:
`@@everyone`

This behaviour on is correct according the official docs, but it seems like the client stumbles over the special everyone type. Using the literal `@everyone` works fine though.

Proposed solution:
Introduce a check on `RoleBehavior#mention` that checks for `guildId.value == id.value` and returns the literal `@everyone` on true instead.

### PR DESCRIPTION
**Pull request by mrbarrientosg**
Fix #94

### CODE REVIEW

File: core/src/main/kotlin/com/gitlab/kordlib/core/behavior/RoleBehavior.kt [hunk 1]
```diff
@@ -37,7 +37,12 @@ interface RoleBehavior : Entity, Strategizable {
     /**
      * The raw mention of this entity.
      */
-    val mention: String get() = "<@&${id.value}>"
+    val mention: String get() {
+        return when(guildId.value == id.value) {
+            true -> "@everyone"
+            false -> "<@&${id.value}>"
+        }
```
Comment (BartArys) [inline core/src/main/kotlin/com/gitlab/kordlib/core/behavior/RoleBehavior.kt:44]: Prefer using `if/else` for binary conditions: https://kotlinlang.org/docs/reference/coding-conventions.html#if-versus-when

```suggestion
        return if(guildId.value == id.value) "@everyone"
        else "<@&${id.value}>"
```

**Review by BartArys — CHANGES_REQUESTED** [review]
Thanks for taking your time to fix this issue!
One small nitpick as per the Kotlin coding conventions.

File: core/src/main/kotlin/com/gitlab/kordlib/core/behavior/RoleBehavior.kt (hunk 1 above)
Comment (mrbarrientosg) [reply core/src/main/kotlin/com/gitlab/kordlib/core/behavior/RoleBehavior.kt]: Hi, thanks you for the tip, I'm going to consider it next time :)

**Review by BartArys — APPROVED** [review]
